version: '3.7'

services:
  backend_container:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    expose:
      - 4000
    ports:
      - 4000:4000
    command: npm run dev
  mongodb_container:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=blub
    restart: always
    expose:
      - ${MONGODB_PORT}
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
