version: '3.7'

services:
  backend_container:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - mongodb_container
    env_file:
      - .env
    expose:
      - ${BACKEND_SERVER_PORT}
    ports:
      - ${BACKEND_SERVER_PORT}:${BACKEND_SERVER_PORT}
    command: npm run dev
  mongodb_container:
    image: mongo:latest
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    restart: always
    expose:
      - ${MONGODB_PORT}
    ports:
      - 27017:${MONGODB_PORT}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
